### ISSUE TITLE
don't use alert()

### ISSUE THREAD

**Issue by maxf** [ministryofjustice/bba#7]
hijacks your browser.

**Comment by Dan-Solo** [comment]
Can I please be removed from this mailing list.

I used to work at the MoJ but left about 6 years ago and yet these keep coming through.

Thanks

________________________________

**Comment by SteveMarshall** [comment]
@Dan-Solo We can't unsubscribe you; you need to visit https://github.com/notifications/subscriptions and unsubscribe from things you don't want to be informed of.
